<h2 style='text-align:center'>Webhooks</h2>
<form action="/webhooks/hook/" method='post'>
<input type="text" placeholder="Username" name='name'>
<input type="url" placeholder="Enter Url" name='url'><br>
<input type="checkbox" value='add_product' name='webhook[]' >Add Product<br>
<input type="checkbox" value='update_product' name='webhook[]' >Update product<br>
<button tyep="submit" value="submit">Submit</button>
</form>