
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h3>Hello!!!</h3>
<h4>For api hit localhost:8080/api</h4>
<h4>For Frontend hit localhost:8080/frontend/index</h4>
<br>
<?php
echo $this->tag->linkTo(['/orderlist/list/', 'Show orderlist', 'class' => 'btn btn-primary']);
echo $this->tag->linkTo(['/productlist', 'Show Productlist', 'class' => 'btn btn-danger']);
echo $this->tag->linkTo(['/orderlist/order/', 'Create Order', 'class' => 'btn btn-dark']);
echo $this->tag->linkTo(['/orderlist/update/', 'Update Order Status', 'class' => 'btn btn-secondary']);
echo $this->tag->linkTo(['/productlist/add/', 'Add Products', 'class' => 'btn btn-info']);
echo $this->tag->linkTo(['/webhooks', 'Add url(Webhooks)', 'class' => 'btn btn-secondary']);

?>
</body>
</html>